os: linux
dist: xenial
language: python
cache: pip
python: 3.8

stages:
  - test
  - deploy

jobs:
  include:
    - name: "Testing"
      stage: test
      if: |
        type = pull_request AND \
        branch = master
      before_script:
        - git remote set-branches --add origin master
        - git fetch
      script:
        - ci/run_tests.sh
    - name: "Deploying"
      stage: deploy
      if: |
        type = push
      script:
        - ci/make_docs.sh
        - python setup.py sdist
      deploy:
        - provider: pages:git
          edge: true
          verbose: true
          cleanup: false
          token: $GITHUB_TOKEN
          keep_history: true
          local_dir: ./docs/build/html/
          on:
            branch: master

        - provider: pypi
          edge: true
          username: __token__
          password: $PYPI_TOKEN
          distributions: "sdist"
          skip_existing: true
          on:
            tags: true

        - provider: releases
          edge: true
          token: $GITHUB_TOKEN
          on:
            tags: true


install:
  - ci/install_dependencies.sh
script:
  - python setup.py install
